FROM nginx:latest

# Configure HTTPS in NGINX for Keycloak Using Docker Compose
# käytti seuraavaa lisäystä:
EXPOSE 80

# RUN apt-get update -y && apt-get upgrade -y && pt-get install -y procps
RUN apt-get update && apt-get install -y procps less
